### ISSUE TITLE
Does coco format need all field?

### ISSUE THREAD

**Issue by sdalxn** [CivilNet/Gemfield#1]
I want to know whether all fields of the coco format are needed, such as "info" "licenses", when I custom my own database as coco format.

Another situation, in the annotation field,
```
annotation{
    "id": int,    
    "image_id": int,
    "category_id": int,
    "segmentation": RLE or [polygon],
    "area": float,
    "bbox": [x,y,width,height],
    "iscrowd": 0 or 1,
}
```
Should I write all the key, such as iscrowd in my json file?

Any suggestion will be appreciated.

**Comment by gemfield** [comment]
@sdalxn : For Detectron, info and licenses are optional, while all fields in "annotation" are mandatory.

**Comment by sdalxn** [comment]
OK，Thank you!
